# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7fd962c4f4882a28365d46bb0c6bbe60a077a6f38155b91090a78db9c69a0db07d9acfbd2ef18864d29d0d65d9f0c589c9b3f25289eb747042bae9f0bbe485f3

test:
  secret_key_base: 6241686a387a5a322ce7f099245c22e6b26bdac2619e23378f2d7a582f7c5a9c81678efc2a1f4b162491b2d56cf40e16fda073d22daad2b2813ab18b29151084

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
